import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { sendPasswordResetEmail } from "@/lib/services/emailHelper";

export async function POST(request: Request) {
  try {
    console.log("[PASSWORD RESET API] Request received");
    
    const { email } = await request.json();

    if (!email) {
      return NextResponse.json(
        { success: false, error: "Email is required" },
        { status: 400 }
      );
    }

    console.log(`[PASSWORD RESET API] Processing reset request for: ${email}`);

    const supabase = await createClient();

    // Step 1: Request password reset from Supabase
    // This generates a token internally but we suppress the default email
    console.log(`[PASSWORD RESET API] Requesting reset token from Supabase...`);
    const { error: resetError } = await supabase.auth.resetPasswordForEmail(email, {
      redirectTo: `${process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000"}/update-password`,
    });

    if (resetError) {
      console.error(`[PASSWORD RESET API] Supabase error:`, resetError.message);
      
      // Detect rate limit error
      if (resetError.message.toLowerCase().includes("rate limit") || resetError.message.toLowerCase().includes("too many")) {
        console.warn(`[PASSWORD RESET API] ⏱️  Rate limit hit - user requested too many reset emails`);
        return NextResponse.json(
          { 
            success: false, 
            error: "Too many password reset requests. Please wait 15 minutes before trying again.",
            code: "RATE_LIMIT"
          },
          { 
            status: 429,
            headers: {
              "Retry-After": "900", // 15 minutes
            }
          }
        );
      }
      
      return NextResponse.json(
        { success: false, error: resetError.message },
        { status: 400 }
      );
    }

    console.log(`[PASSWORD RESET API] ✓ Reset token generated by Supabase`);

    // Step 2: Build custom reset link
    // The reset link is generated by Supabase and emailed to user
    // We need to send our own version via Gmail
    const resetLink = `${process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000"}/update-password`;

    // Step 3: Get user name if possible (from profiles table)
    const { data: profile } = await supabase
      .from("profiles")
      .select("full_name")
      .eq("email", email)
      .single();

    const userName = profile?.full_name || "User";

    console.log(`[PASSWORD RESET API] Sending custom reset email via Gmail...`);

    // Step 4: Send password reset email via our custom Gmail service
    // Note: Gmail is optional - Supabase will always send an email anyway
    let emailSent = false;
    try {
      emailSent = await sendPasswordResetEmail(
        email,
        userName,
        resetLink
      );
    } catch (emailError) {
      console.error(`[PASSWORD RESET API] Error sending custom Gmail email:`, emailError instanceof Error ? emailError.message : emailError);
      console.error(`[PASSWORD RESET API] Stack:`, emailError instanceof Error ? emailError.stack : "");
    }

    if (emailSent) {
      console.log(`[PASSWORD RESET API] ✓ Password reset email sent via Gmail`);
      return NextResponse.json({
        success: true,
        message: "Password reset email sent to " + email,
      });
    } else {
      console.warn(`[PASSWORD RESET API] Custom Gmail email send failed`);
      console.warn(`[PASSWORD RESET API] ✓ Supabase has sent a standard reset email to ${email}`);
      console.warn(`[PASSWORD RESET API] The password reset link is on its way!`);
      console.warn(`[PASSWORD RESET API] Gmail integration is optional - Supabase email delivery is working fine.`);
      console.warn(`[PASSWORD RESET API] If you want custom Gmail emails, run: GET /api/email/debug-full`);
      
      // Even though Gmail failed, Supabase sent the email successfully
      // So return success = true since user WILL get the reset email
      return NextResponse.json({
        success: true,
        message: "Password reset email sent successfully! Check your inbox.",
        note: "Using Supabase email delivery (Gmail integration optional)"
      });
    }
  } catch (error) {
    console.error("[PASSWORD RESET API] Error:", error);
    return NextResponse.json(
      {
        success: false,
        error: error instanceof Error ? error.message : "Internal server error",
      },
      { status: 500 }
    );
  }
}
