"use client";

import React, { useState, useRef } from "react";
import { UploadCloud, X, Loader2, Image as ImageIcon } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
import { ProductImage } from "@/lib/types/product";

interface ImageUploadProps {
  onUploadSuccess: (image: ProductImage) => void;
  onRemove?: (url: string) => void;
  existingImages?: ProductImage[];
  multiple?: boolean;
}

export function ImageUpload({
  onUploadSuccess,
  onRemove,
  existingImages = [],
  multiple = false,
}: ImageUploadProps) {
  const [isDragging, setIsDragging] = useState(false);
  const [isUploading, setIsUploading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const handleDragOver = (e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(true);
  };

  const handleDragLeave = () => {
    setIsDragging(false);
  };

  const handleDrop = async (e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(false);
    const files = Array.from(e.dataTransfer.files);
    if (files.length > 0) {
      await processFiles(multiple ? files : [files[0]]);
    }
  };

  const handleFileChange = async (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files) {
      const files = Array.from(e.target.files);
      await processFiles(multiple ? files : [files[0]]);
    }
  };

  const processFiles = async (files: File[]) => {
    setError(null);
    for (const file of files) {
      if (!file.type.startsWith("image/")) {
        setError("Only image files are allowed.");
        continue;
      }
      if (file.size > 5 * 1024 * 1024) {
        setError("File size should not exceed 5MB.");
        continue;
      }

      setIsUploading(true);
      try {
        const formData = new FormData();
        formData.append("file", file);

        const response = await fetch("/api/upload", {
          method: "POST",
          body: formData,
        });

        const data = await response.json();

        if (!response.ok) {
          throw new Error(data.error || "Failed to upload image");
        }

        // Return the partial ProductImage data
        onUploadSuccess({
          id: "", // will be generated by the database if needed, or omitted
          product_id: "", // will be linked during product save
          url: data.url,
          is_thumbnail: existingImages.length === 0,
          display_order: existingImages.length,
          provider: data.provider,
          public_id: data.public_id,
          file_size: data.file_size,
          mime_type: data.mime_type,
        });
      } catch (err: any) {
        setError(err.message || "An error occurred during upload.");
      }
    }
    setIsUploading(false);
    if (fileInputRef.current) {
      fileInputRef.current.value = "";
    }
  };

  return (
    <div className="space-y-4">
      {/* Upload Area */}
      <div
        className={`relative border-2 border-dashed rounded-xl p-8 text-center transition-colors ${
          isDragging
            ? "border-accent-gold bg-accent-gold/5"
            : "border-border/60 hover:border-accent-gold/50 bg-surface/30"
        } ${isUploading ? "opacity-50 pointer-events-none" : ""}`}
        onDragOver={handleDragOver}
        onDragLeave={handleDragLeave}
        onDrop={handleDrop}
      >
        <input
          type="file"
          ref={fileInputRef}
          className="hidden"
          accept="image/*"
          multiple={multiple}
          onChange={handleFileChange}
        />
        
        <div className="flex flex-col items-center justify-center gap-3">
          <div className="w-12 h-12 rounded-full bg-accent-gold/10 flex items-center justify-center text-accent-gold">
            {isUploading ? <Loader2 className="animate-spin" /> : <UploadCloud />}
          </div>
          <div>
            <p className="text-foreground dark:text-white font-medium">
              Click or drag images here to upload
            </p>
            <p className="text-sm text-muted mt-1">
              Supports JPG, PNG, WEBP up to 5MB. Powered by Cloudinary & ImageKit.
            </p>
          </div>
          <button
            type="button"
            className="px-4 py-2 mt-2 bg-surface border border-border rounded-lg text-sm font-medium hover:border-accent-gold transition-colors cursor-pointer"
            onClick={() => fileInputRef.current?.click()}
          >
            Browse Files
          </button>
        </div>
      </div>

      {/* Error Message */}
      <AnimatePresence>
        {error && (
          <motion.div
            initial={{ opacity: 0, y: -10 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0 }}
            className="p-3 text-sm text-red-500 bg-red-500/10 border border-red-500/20 rounded-lg"
          >
            {error}
          </motion.div>
        )}
      </AnimatePresence>

      {/* Image Gallery */}
      {existingImages.length > 0 && (
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mt-4">
          <AnimatePresence>
            {existingImages.map((img, index) => (
              <motion.div
                key={img.public_id || img.url}
                initial={{ opacity: 0, scale: 0.9 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0, scale: 0.9 }}
                className="relative group aspect-square rounded-lg overflow-hidden border border-border/50 bg-black/5"
              >
                <img
                  src={img.url}
                  alt={`Upload ${index}`}
                  className="w-full h-full object-cover"
                />
                <div className="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center gap-2 backdrop-blur-[2px]">
                  {onRemove && (
                    <button
                      type="button"
                      onClick={() => onRemove(img.url)}
                      className="p-2 bg-red-500 text-white rounded-full hover:bg-red-600 transition-colors cursor-pointer"
                      title="Remove image"
                    >
                      <X size={16} />
                    </button>
                  )}
                </div>
                {img.is_thumbnail && (
                  <span className="absolute top-2 left-2 px-2 py-1 text-[10px] font-bold uppercase bg-accent-gold text-black rounded">
                    Thumbnail
                  </span>
                )}
                <span className="absolute bottom-2 right-2 px-1.5 py-0.5 text-[9px] font-mono uppercase bg-black/70 text-white rounded opacity-50">
                  {img.provider || "url"}
                </span>
              </motion.div>
            ))}
          </AnimatePresence>
        </div>
      )}
    </div>
  );
}
